/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Omega Point mult based': '欧米伽点数加成基于',
    'Omega Upgrades': '欧米伽升级',
    'on current Energy': '当前的能源',
    'on current Omega.': '当前的欧米伽.',
    'PVP Legend': 'PVP传奇',
    'RESET OMEGA UPGRADES': '重置欧米伽升级',
    'RESIMULATION': '重新模拟',
    'Resimulate for': '重新模拟',
    'Simulation': '模拟',
    'reset.': '重置.',
    'Raise Expansion Upgrade': '提升扩展升级',
    'Raise max Electrons by ^': '将最大电子数提高^',
    'Raise the power of all': '提升所有的力量',
    'Remove the max': '移除最大',
    'Stage': '阶段',
    'Stage Gold Exponent Multiplier': '阶段金指数乘数',
    '???': '???',
    'EXPANSION': '扩张',
    'Expansion': '扩张',
    'HOTKEYS': '快捷键',
    'Hybrid': '混合',
    'Improves the resimulation': '改善重新模拟',
    'Info': '信息',
    'generator': '发生器',
    'generators': '发生器',
    'Generator': '发生器',
    'Generators': '发生器',
    'GENERATORS': '发生器',
    'Prestige doesn\'t': '声望不',
    'prestige limit.': '声望上限。',
    'Reset Electrons for Atoms': '重置电子的原子',
    'Expansion Generator': '扩展发生器',
    'PRESTIGE': '声望',
    'automatic': '自动',
    'to damage per second': '损坏每秒',
    'to EP gain': '到EP收益',
    'to every generator': '到每个发生器',
    'to all': '到所有',
    'to all generators': '到所有发生器',
    ' $x': '你有 $x',
    'upgrade': '升级',
    'upgrades': '升级',
    'Upgrade': '升级',
    'Upgrades': '升级',
    'to gold per second': '到黄金每秒',
    'prestige autobuyer.': '声望自动购买器.',
    'Prestige Autobuyer.': '声望自动购买器.',
    'ON NEXT EXPANSION': '下一步扩张',
    'Omega Points': '欧米伽点数',
    'All Mult': '全部加成',
    'all generators based': '基于所有发生器',
    'Alpha': '阿尔法',
    "Alpha Beta Gamma": "阿尔法贝塔伽马",
    'Amount': '数量',
    'Atoms': '原子',
    'autobuyer': '自动购买器',
    'autobuyers': '自动购买器',
    'Autobuyers': '自动购买器',
    'Autobuyer': '自动购买器',
    'Automatically Fight': '自动战斗',
    'current OP': '当前OP',
    'electricity': '电力',
    'Fighting Mode': '战斗模式',
    'Gamma': '伽马',
    'Generator creates': '发生器创建',
    'Generator Prestige': '发生器声望',
    'generator prestiges': '发生器声望',
    'Gold': '黄金',
    'Gold/DPS Multiplier': '黄金/DPS 倍数',
    'Heroes': '英雄',
    'Heroe': '英雄',
    'Hero': '英雄',
    'Farmer': '农民',
    'highest amount': '最高数量',
    'highest EP': '最高EP',
    'Level': '等级',
    'Keep some Electrons': '保留一些电子',
    'Mode': '模式',
    'Mult': '加成',
    'Multiplier': '倍数',
    'Omega': '欧米伽',
    'omega': '欧米伽',
    'Per Second': '每秒',
    'Per Sec': '每秒',
    'Prestige': '声望',
    'stages completed': '阶段完成',
    'stages in simulation': '模拟阶段',
    'test': '测试',
    'when purchasing a Generator': '购买发生器时',
    'when resetting for Atoms': '重置原子时',
    'x Gold Per Second': 'x 黄金每秒',
    'Currently': '当前',
    'Electricity': '电力',
    'Electrons': '电子',
    'Electron effect': '电子效率',
    'first': '第一个',
    'Max Electrons': '最大电子',
    'They multiply all mult gain by': '他们将所有多重收益乘以',
    'They increase something by': '他们增加了一些',
    'Not unlocked': '未解锁',
    'Multiply EP gain by': 'EP增益乘以',
    'Increase your all': '提升你全部',
    'Bought': '已买',
    'Current': '当前',
    'Current multiplier': '当前倍数',
    'Beta': '贝塔',
    'BECOME OMEGA': '成为欧米伽',
    'autobuyers when becoming': '自动购买器时成为',
    'Atom reset no longer resets Electrons': '原子重置不再重置电子',
    'at heavily reduced rate': '大幅降低',
    'formulas by': '公式',
    'Get the ability to skip': '获得跳过的能力',
    'Multiply your all': '乘以你全部',
    'of first prestiges': '第一声望',
    'Points': '点数',
    'to the power of Electron gain': '电子增益的力量',
    'Point mult based': '点数加成基于',
    'Point Multiplier': '点数倍数',
    'Increase 2nd electron upgrade': '提高第二电子升级',
    'Increase 2nd Electron upgrade by': '提高第二电子升级',
    'expansion': '扩张',
    'expansions': '扩张',
    'Gain more EP based on': '获得更多EP基于',
    'Generator and EP mult autobuyers': '发生器和EP加成自动购买器',
    'Increase max prestige': '提升最大声望',
    'Increase prestige effect by': '提升声望效果',
    'Increase prestige multiplier': '提升声望倍数',
    'Increase the electricity price reduction effect': '增加电力降价效果',
    'Increase the multiplier you get': '提高倍数当你获得',
    'It increases electricity effect by': '通过增加电力效果',
    'M: Buys all generators and all mult': 'M：购买所有发生器和全部加成',
    'A/B/G Upgrade': 'A/B/G 升级',
    'and all mult': '和全部加成',
    'and you keep all': '和保留你的全部',
    'on current': '在当前',
    'Multiply Electron gain by': '电子增益乘以',
    'Gain 2x more gold and': '获得2倍的黄金和',
    'Gain 3x more gold for': '获得3倍的黄金',
    'Gain 5x more DPS for': '获得5倍的DPS',
    'Gain a 20x multiplier': '获得20倍的乘数',
    'on': '开启',
    'Get 100% of EP you would get': '获得100％扩张点你会得到',
    'DPS for every 4th Hybrid': 'DPS为每4个混合',
    'Gamma unlocked!': '伽玛已解锁！',
    'makes electricity stronger.': '使电力更强大。',
    'OMEGA': '欧米伽',
    'on highest ever': '有史以来最高',
    'SIMULATION': '模拟',
    'Unlocked!': '已解锁!',
    'ALPHA BETA GAMMA': '阿尔法贝塔伽马',
    'Alpha, Beta and': '阿尔法，贝塔和',
    'are 1.5x stronger for every': '1.5x更强为每个',
    'AUTOBUYERS': '自动购买器',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'But like with all the other prestige mechanics, you get stronger.': '但就像所有其他声望机制一样，你会变得更强大。',
    'Beta costs EP and Gamma costs electricity. You can use them to buy different upgrades!': '贝塔消耗扩张点和伽玛消耗电力。你可以使用它们来购买不同的升级!',
    'Becoming Omega resets everything you\'ve done so far, but with some big rewards.': '成为欧米伽会重置你到目前为止所做的一切，但会有一些巨大的回报。',
    'Autobuyers do things for you automatically! They can automatically prestige, buy generators,': '自动发生器为你自动地做事情!他们可以自动声望、自动购买发生器',
    'You unlock a new set of generators, and upgrades. Omega Generators produce Omega.': '你解锁了一组新的发生器，和升级。欧米伽发生器产生欧米伽。',
    'You can purchase three different currencies; Alpha, Beta and Gamma. Alpha costs energy,': '你可以购买三种不同的货币;阿尔法、贝塔和伽玛。阿尔法成本是能量,',
    'When you expand you reset everything and gain expansion points (EP). They are used to': '当你扩张时，你重置了所有的东西并获得了扩张点(EP)。他们用于',
    'when you expand with the expansion autobuyer. Just type in however much you want.': '当你扩张和扩张自动购买一起。你想输入多少就输入多少。',
    'what stage you\'re at. Later you will be able to Resimulate, resetting your simulation back to the beginning.': '你所处的阶段。稍后，您将能够重新模拟，将模拟重新设置为开始。',
    'Use your gold to upgrade your three heroes. You also get a multiplier to your gold income based on': '',
    'upgrades are automatically unlocked every 100x electricity, starting at 1.': '升级会自动解锁每 100x 电力,从1开始。',
    'upgrades is kind of like a skill tree. You need to buy every previous upgrade to be able to purchase': '升级就像一个技能树。你需要购买之前的每一个升级才能购买',
    'upgrade expansion generators or your EP gain multiplier.': '升级扩张发生器或扩张点获得倍数。',
    'There are two different modes you can be in: Gold Mode and Fighting Mode.': '你可以进入两种不同的模式:黄金模式和战斗模式。',
    'The upgrades costs Omega, and it goes up every time you buy another upgrade.': '升级需要消耗欧米伽的成本，并且每次你购买另一个升级时成本都会上升。',
    'the next. If you\'re unhappy with a choice you made, or want to try a different build, you can reset for free!': '下一个。如果您对所做的选择不满意，或者想尝试不同的构建，您可以免费重置!',
    'or even expand. To activate them just check the box. You can decide how much EP you wanna get': '甚至扩大。要激活它们，请勾选方框。你可以决定你想要多少扩张点',
    'In the simulation you have to fight your way through hordes of monsters, and infinite floors.': '在模拟游戏中，你必须通过成群的怪物和无限的楼层去战斗。',
    'In Gold Mode you will earn gold, and in Fighting Mode you will fight (duh).': '在黄金模式下你将获得金币，在战斗模式下你将战斗(废话)。',
    'generators works like normal generators, except they make electricity instead of energy.': '发生器的工作原理与普通发电机类似，只是它们代替电能发电。',
    'Electricity reduces the cost of the all mult upgrade.': '力减少了所有升级的成本。',
    'Increase the effect of Expansion Upgrade 13 by': '通过以下方式增强扩张升级13的效果',
    'Increase EP gain based on time spend in this expansion': '根据此扩张中的时间花费来增加扩张点收益',
    'Gain a multiplier to': '获得乘数',
    'Gain a multiplier': '获得乘数',
    'is every 29th instead': '是每一个第29，而不是',
    'The 3 previous upgrades': '之前的3个升级',
    'Increase Alpha': '提高阿尔法',
    'Increase Beta': '提高贝塔',
    'Increase Gamma': '提高伽马',
    'Upgrade 5 autobuyer': '升级5个自动购买器',
    'Increase Electron gain': '增加电子增益',
    'Expand for': '扩展为',
    'on Expansion every sec': '每秒扩张一次',
    'Multiply all mult gain based on highest ever': '根据有史以来的最高水平乘以所有多重收益',
    'Multiply all expansion generators by': '将所有扩张发生器乘以',
    'Multiplier to stage gold exponent': '乘以黄金指数',
    'expansion generators': '扩张发生器',
    'for each stage beaten': '每一个被打败的阶段',
    'current': '当前',
    'Atom reset no longer resets': '原子重置不再重置',
    'It multiplies your expansion generator by xx': '它将您的扩张发生器乘以xx',
    'It\'s very worth it, and is necessary to progress.': '这是非常值得的，也是进步的必要条件。',
    'Reset Electrons for': '重置电子对',
    'when resetting for': '当重置',
    'mult gain by': '多重收益',
    'mult gain based': '多重收益基于',
    'Keep some': '保留一些',
    'highest': '最高',
    'Alpha Beta': '阿尔法 贝塔',
    'DPS Multiplier': 'DPS 倍数',
    'and your all mult. The second generator creates the first, the third creates the second and so on.': '和你的全部加成。 第二个发生器创建第一个，第三个发生器创建第二个，依此类推。',
    'The first generator makes energy. Energy is the main currency you use to upgrade your generators': '第一台发生器产生能量。能量是你用来升级发生器的主要货币',
    'Prestige resets your generators and your Energy, but you get a 2x multiplier to everything.': '声望会重置你的发生器和能量，但你的所有东西会得到x2的加成。',

    //原样
    'by': 'by',
    'DPS': 'DPS',
    'EP': '扩张点',
    'OP': '欧米伽点',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "First ": "第一",
    "Second ": "第二",
    "Third ": "第三",
    "Fourth ": "第四",
    "Fifth ": "第五",
    "Sixth ": "第六",
    "Seventh ": "第七",
    "Eighth ": "第八",
    "Unlock ": "解锁 ",
    "Simulation ": "模拟 ",
    "Alpha Beta Gamma ": "阿尔法贝塔伽马",
    "based on ": "基于",
    "Gold ": "黄金",
    "Expansion ": "扩张",
    "Omega ": "欧米伽",
    "Cost: ": "成本: ",
    "Multiply all generators by": "将所有发生器乘以",
    "It divides your all mult cost by": "它会将您的全部加成的费用除以",
    "You have": "你有",
    "You need": "你需要",
    'Become Omega for': '把欧米伽变成',
    "Multiply first expansion generator by ": "将第一个扩张发生器乘以",
    "every ": "每",
    "Multiplier to DPS and ": "乘以DPS和",
    "Mult:": "加成:",
    "Current: ": "当前: ",
    "It increases electricity effect by ": "它增加电效应",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    ": x": ": x",
    " Autobuyer": "自动购买器",
    ' EP': '扩张点',
    ' OP': '欧米伽点',
    " Energy": "能量",
    " Electricity": " 电力",
    " Electrons": "电子",
    " First Generators Bought": " 第一发生器买",
    " Second Generators Bought": " 第二发生器已买",
    " Third Generators Bought": " 第三发生器已买",
    " Fourth Generators Bought": " 第四发生器已买",
    " Fifth Generators Bought": " 第五发生器已买",
    " Sixth Generators Bought": " 第六发生器已买",
    " Seventh Generators Bought": " 第七发生器已买",
    " Eighth Generators Bought": " 第八发生器已买",
    " Alpha": "阿尔法",
    " Beta": "贝塔",
    " Gamma": "伽马",
    " Gold": "黄金",
    " Atoms": "原子",
    " Omega": "欧米伽",
    " Omega Points": "欧米伽点",
    " Expansion Points": "扩张点",
    " total levels bought": "总等级已购买",
    " root Atom reset cost": "根原子重置成本",
    " Gold Farmer": "黄金农夫",
    " PVP Legend": "PVP传奇",
    " Upgrade 5 effect": "升级 5 效果",
    "Infinite": "无限",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Get a (.+) multiplier$/, '获得一个 $1 倍数'],
    [/^You\'re getting (.+) Energy per second$/, '您每秒获得 $1 能量'],
    [/^You\'re getting (.+) Electricity per second$/, '您每秒获得 $1 电力'],
    [/^You\'re getting (.+) Omega per second$/, '您每秒获得 $1 欧米伽'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);