/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Omega Point mult based': '欧米伽点数加成基于',
    'Omega Upgrades': '欧米伽升级',
    'on current Energy': '当前的能源',
    'on current Omega.': '当前的欧米伽.',
    'PVP Legend': 'PVP传奇',
    'RESET OMEGA UPGRADES': '重置欧米伽升级',
    'RESIMULATION': '重新模拟',
    'Resimulate for': '重新模拟',
    'Simulation': '模拟',
    'reset.': '重置.',
    'Raise Expansion Upgrade': '提升扩展升级',
    'Raise max Electrons by ^': '将最大电子数提高^',
    'Raise the power of all': '提升所有的力量',
    'Remove the max': '移除最大',
    'Stage': '阶段',
    'Stage Gold Exponent Multiplier': '阶段金指数乘数',
    '???': '???',
    'EXPANSION': '扩张',
    'Expansion': '扩张',
    'HOTKEYS': '快捷键',
    'Hybrid': '混合',
    'Improves the resimulation': '改善重新模拟',
    'Info': '信息',
    'generator': '发生器',
    'generators': '发生器',
    'Generator': '发生器',
    'Generators': '发生器',
    'GENERATORS': '发生器',
    'Prestige doesn\'t': '声望不',
    'prestige limit.': '声望上限。',
    'Reset Electrons for Atoms': '重置电子的原子',
    'Expansion Generator': '扩展发生器',
    'PRESTIGE': '声望',
    'automatic': '自动',
    'to damage per second': '损坏每秒',
    'to EP gain': '到EP收益',
    'to every generator': '到每个发生器',
    'to all': '到所有',
    'to all generators': '到所有发生器',
    'You have $x': '你有 $x',
    'upgrade': '升级',
    'upgrades': '升级',
    'Upgrade': '升级',
    'Upgrades': '升级',
    'to gold per second': '到黄金每秒',
    'prestige autobuyer.': '声望自动购买者.',
    'Prestige Autobuyer.': '声望自动购买者.',
    'ON NEXT EXPANSION': '下一步扩张',
    'Omega Points': '欧米伽点数',
    'All Mult': '全部加成',
    'all generators based': '基于所有发生器',
    'Alpha': '阿尔法',
    "Alpha Beta Gamma": "阿尔法贝塔伽马",
    'Amount': '数量',
    'Atoms': '原子',
    'autobuyer': '自动购买者',
    'autobuyers': '自动购买者',
    'Autobuyers': '自动购买者',
    'Autobuyer': '自动购买者',
    'Automatically Fight': '自动战斗',
    'current OP': '当前OP',
    'electricity': '电力',
    'Fighting Mode': '战斗模式',
    'Gamma': '伽马',
    'Generator creates': '发生器创建',
    'Generator Prestige': '发生器声望',
    'generator prestiges': '发生器声望',
    'Gold': '黄金',
    'Gold/DPS Multiplier': '黄金/DPS 倍数',
    'Heroes': '英雄',
    'Heroe': '英雄',
    'Hero': '英雄',
    'Farmer': '农民',
    'highest amount': '最高数量',
    'highest EP': '最高EP',
    'Level': '等级',
    'Keep some Electrons': '保留一些电子',
    'Mode': '模式',
    'Mult': '加成',
    'Multiplier': '倍数',
    'Omega': '欧米伽',
    'omega': '欧米伽',
    'Per Second': '每秒',
    'Per Sec': '每秒',
    'Prestige': '声望',
    'stages completed': '阶段完成',
    'stages in simulation': '模拟阶段',
    'test': '测试',
    'when purchasing a Generator': '购买发生器时',
    'when resetting for Atoms': '重置原子时',
    'x Gold Per Second': 'x 黄金每秒',
    'Currently': '当前',
    'Electricity': '电力',
    'Electrons': '电子',
    'Electron effect': '电子效率',
    'first': '第一个',
    'Max Electrons': '最大电子',
    'They multiply all mult gain by': '他们将所有多重收益乘以',
    'They increase something by': '他们增加了一些',
    'Not unlocked': '未解锁',
    'Multiply EP gain by': 'EP增益乘以',
    'Increase your all': '提升你全部',
    'Bought': '已买',
    'Current': '当前',
    'Current multiplier': '当前倍数',
    'Beta': '贝塔',
    'BECOME OMEGA': '成为欧米伽',
    'autobuyers when becoming': '自动购买者时成为',
    'Atom reset no longer resets Electrons': '原子重置不再重置电子',
    'at heavily reduced rate': '大幅降低',
    'formulas by': '公式',
    'Get the ability to skip': '获得跳过的能力',
    'Multiply your all': '乘以你全部',
    'of first prestiges': '第一声望',
    'Points': '点数',
    'to the power of Electron gain': '电子增益的力量',
    'Point mult based': '点数加成基于',
    'Point Multiplier': '点数倍数',
    'Increase 2nd electron upgrade': '提高第二电子升级',
    'Increase 2nd Electron upgrade by': '提高第二电子升级',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'The first generator makes energy. Energy is the main currency you use to upgrade your generators': '第一台发生器产生能量。能量是你用来升级发生器的主要货币',
    'Prestige resets your generators and your Energy, but you get a 2x multiplier to everything.': '声望会重置你的发生器和能量，但你的所有东西会得到x2的加成。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "First ": "第一",
    "Second ": "第二",
    "Third ": "第三",
    "Fourth ": "第四",
    "Fifth ": "第五",
    "Sixth ": "第六",
    "Seventh ": "第七",
    "Eighth ": "第八",
    "Unlock ": "解锁 ",
    "You have 0 ": "你有 0 ",
    "You have x ": "你有 x ",
    "You have X ": "你有 X ",
    "Simulation ": "模拟 ",
    "Alpha Beta Gamma ": "阿尔法贝塔伽马",
    "based on ": "基于",
    "Gold ": "黄金",
    "Expansion ": "扩张",
    "Omega ": "欧米伽",
    "Cost: ": "成本: ",
    "Multiply all generators by": "将所有发生器乘以",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    ": x": ": x",
    " Autobuyer": "自动购买者",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^You need (.+) Energy$/, '你需要 $1 能量'],
    [/^You have (.+) Energy$/, '你有 $1 能量'],
    [/^You have (.+) Electrons$/, '你有 $1 电子'],
    [/^You\'re getting (.+) Energy per second$/, '您每秒获得 $1 能量'],
    [/^You\'re getting (.+) Electricity per second$/, '您每秒获得 $1 电力'],
    [/^You\'re getting (.+) Omega per second$/, '您每秒获得 $1 欧米伽'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);